import test from 'node:test';
import assert from 'node:assert/strict';
import {
  callGoogleTts,
  callGoogleImage,
  callGoogleMusic,
  startGoogleVideo,
  getGoogleVideoStatus,
  personaVoice,
} from './google-media.mjs';

function jsonResponse(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {'content-type': 'application/json'},
  });
}

test('persona voices are distinct and configurable without client release', () => {
  assert.equal(personaVoice('zane', {}), 'Charon');
  assert.equal(personaVoice('nirvana', {}), 'Sulafat');
  assert.equal(personaVoice('zane', {WESI_ZANE_TTS_VOICE: 'Iapetus'}), 'Iapetus');
  assert.equal(personaVoice('nirvana', {WESI_NIRVANA_TTS_VOICE: 'not-a-voice'}), 'Sulafat');
});

test('TTS retries one provider 500 and returns bounded inline WAV', async () => {
  let calls = 0;
  let requestBody = null;
  const fetchImpl = async (_url, init) => {
    calls++;
    requestBody = JSON.parse(init.body);
    if (calls === 1) return jsonResponse({error: {message: 'rare audio failure'}}, 500);
    return jsonResponse({
      steps: [{
        type: 'model_output',
        content: [{type: 'audio', mime_type: 'audio/wav', sample_rate: 24000, data: Buffer.from('wav').toString('base64')}],
      }],
    });
  };

  const result = await callGoogleTts(
    {persona: 'zane', text: 'Проверка голоса.'},
    'gemini-key',
    {fetchImpl, env: {}},
  );

  assert.equal(calls, 2);
  assert.equal(result.ok, true);
  assert.equal(result.media.kind, 'tts');
  assert.equal(result.media.mimeType, 'audio/wav');
  assert.equal(result.media.voice, 'Charon');
  assert.equal(Buffer.from(result.media.data, 'base64').toString(), 'wav');
  assert.equal(requestBody.model, 'gemini-3.1-flash-tts-preview');
  assert.equal(requestBody.generation_config.speech_config[0].voice, 'Charon');
});

test('TTS rejects unknown persona before provider call', async () => {
  let called = false;
  const result = await callGoogleTts(
    {persona: 'system', text: 'test'},
    'gemini-key',
    {fetchImpl: async () => { called = true; return jsonResponse({}); }},
  );
  assert.equal(result.ok, false);
  assert.equal(result.code, 'WAI_BAD_MEDIA_REQUEST');
  assert.equal(called, false);
});

test('image adapter allowlists format and extracts generated bytes', async () => {
  let body = null;
  const result = await callGoogleImage(
    {prompt: 'Минималистичная обложка', aspectRatio: '16:9', imageSize: '2K'},
    'gemini-key',
    {fetchImpl: async (_url, init) => {
      body = JSON.parse(init.body);
      return jsonResponse({steps: [{type: 'model_output', content: [{type: 'image', mime_type: 'image/png', data: Buffer.from('png').toString('base64')}]}]});
    }},
  );
  assert.equal(result.ok, true);
  assert.equal(result.media.kind, 'image');
  assert.equal(result.media.aspectRatio, '16:9');
  assert.equal(body.model, 'gemini-3.1-flash-image');
  assert.equal(body.response_format.image_size, '2K');
});

test('Lyria clip uses Gemini key and returns MP3 plus lyrics', async () => {
  let body = null;
  const result = await callGoogleMusic(
    {prompt: 'Тёмный атмосферный trap beat, instrumental only', mode: 'clip'},
    'gemini-key',
    {fetchImpl: async (_url, init) => {
      body = JSON.parse(init.body);
      return jsonResponse({
        output_audio: {type: 'audio', mime_type: 'audio/mpeg', data: Buffer.from('mp3').toString('base64')},
        output_text: '[Instrumental]\nDark trap structure',
      });
    }},
  );
  assert.equal(result.ok, true);
  assert.equal(body.model, 'lyria-3-clip-preview');
  assert.equal(result.media.kind, 'music');
  assert.equal(result.media.mimeType, 'audio/mpeg');
  assert.equal(result.media.mode, 'clip');
  assert.match(result.media.lyrics, /Dark trap/);
  assert.equal(Buffer.from(result.media.data, 'base64').toString(), 'mp3');
});

test('Lyria Pro can request WAV explicitly', async () => {
  let body = null;
  const result = await callGoogleMusic(
    {prompt: 'Полноценная композиция с интро и аутро', mode: 'pro', format: 'wav'},
    'gemini-key',
    {fetchImpl: async (_url, init) => {
      body = JSON.parse(init.body);
      return jsonResponse({steps: [{type: 'model_output', content: [{type: 'audio', mime_type: 'audio/wav', data: Buffer.from('wavmusic').toString('base64')}]}]});
    }},
  );
  assert.equal(result.ok, true);
  assert.equal(body.model, 'lyria-3-pro-preview');
  assert.equal(body.response_format.mime_type, 'audio/wav');
  assert.equal(result.media.mimeType, 'audio/wav');
  assert.equal(result.media.mode, 'pro');
});

test('video adapter creates one bounded Veo operation', async () => {
  let url = '';
  let body = null;
  const result = await startGoogleVideo(
    {prompt: 'Короткий кинематографичный пролёт', aspectRatio: '9:16', resolution: '1080p', durationSeconds: '4', quality: 'fast'},
    'gemini-key',
    {fetchImpl: async (u, init) => {
      url = String(u);
      body = JSON.parse(init.body);
      return jsonResponse({name: 'operations/video-test-1'});
    }},
  );
  assert.equal(result.ok, true);
  assert.match(url, /veo-3\.1-fast-generate-preview:predictLongRunning$/);
  assert.equal(body.parameters.numberOfVideos, 1);
  assert.equal(body.parameters.aspectRatio, '9:16');
  assert.equal(body.parameters.durationSeconds, '8', '1080p must use an 8-second request');
});

test('video status keeps provider URI in server-to-server result only', async () => {
  const result = await getGoogleVideoStatus(
    'operations/video-test-1',
    'gemini-key',
    {fetchImpl: async () => jsonResponse({
      done: true,
      response: {generateVideoResponse: {generatedSamples: [{video: {uri: 'https://provider.example/private/video'}}]}},
    })},
  );
  assert.equal(result.ok, true);
  assert.equal(result.done, true);
  assert.equal(result.failed, false);
  assert.equal(result.providerUri, 'https://provider.example/private/video');
});

test('video status rejects path traversal operation names', async () => {
  let called = false;
  const result = await getGoogleVideoStatus(
    '../secret',
    'gemini-key',
    {fetchImpl: async () => { called = true; return jsonResponse({}); }},
  );
  assert.equal(result.ok, false);
  assert.equal(result.code, 'WAI_BAD_MEDIA_REQUEST');
  assert.equal(called, false);
});
