function payload(record) {
  if (!record) return {};
  try {
    const raw = record.get("payload");
    if (raw && typeof raw === "object" && !Array.isArray(raw)) return raw;
    if (typeof raw === "string" && raw.trim()) return JSON.parse(raw);
  } catch (_) {}
  return {};
}
function rows(e, ctx, coll) {
  try { return e.app.findRecordsByFilter("wesios_records", "owner={:owner} && coll={:coll} && deleted=false", "stamp", 0, 0, {owner:ctx.ownerId,coll}); }
  catch (_) { return []; }
}
function recordById(e,ctx,coll,id){try{return e.app.findFirstRecordByFilter("wesios_records","owner={:owner} && coll={:coll} && rid={:rid} && deleted=false",{owner:ctx.ownerId,coll,rid:id});}catch(_){return null;}}
function saveNew(e,ctx,coll,id,value){const now=new Date().toISOString(),c=e.app.findCollectionByNameOrId("wesios_records"),r=new Record(c);r.set("owner",ctx.ownerId);r.set("org","wesi-inc");r.set("coll",coll);r.set("rid",id);r.set("payload",value);r.set("stamp",now);r.set("deleted",false);e.app.save(r);}
function parseDate(value){const d=new Date(String(value||""));return Number.isFinite(d.getTime())?d.toISOString():null;}
function listStrings(value,max=50){if(!Array.isArray(value))return[];const out=[];for(const raw of value.slice(0,max)){const v=String(raw||"").trim().slice(0,180);if(v&&out.indexOf(v)<0)out.push(v);}return out;}
function safeProject(p){return{id:String(p.id||""),title:String(p.title||""),description:String(p.description||""),owner:String(p.owner||""),tags:Array.isArray(p.tags)?p.tags.map(String).slice(0,30):[],startDate:p.startDate||null,endDate:p.endDate||null,archived:p.archived===true,updatedAt:p.updatedAt||null};}
function safeItem(p){return{id:String(p.id||""),projectId:String(p.projectId||""),title:String(p.title||""),description:String(p.description||""),kind:String(p.kind||"phase"),status:String(p.status||"planned"),assignee:String(p.assignee||""),startDate:p.startDate||null,endDate:p.endDate||null,progress:Number(p.progress||0),order:Number(p.order||0),dependencyIds:Array.isArray(p.dependencyIds)?p.dependencyIds.map(String).slice(0,50):[],linkedTaskIds:Array.isArray(p.linkedTaskIds)?p.linkedTaskIds.map(String).slice(0,50):[],updatedAt:p.updatedAt||null};}
function projectExists(e,ctx,id){return !!recordById(e,ctx,"roadmap_projects",id);}

module.exports={
 definitions:function(e,ctx){if(!ctx.isOwner&&ctx.modules.indexOf("roadmap")<0)return[];return[
  {name:"roadmap_list",description:"Прочитать реальные проекты и вехи Roadmap WesiOS.",parameters:{type:"object",properties:{projectId:{type:"string"},includeArchived:{type:"boolean"},limit:{type:"integer",minimum:1,maximum:200}}}},
  {name:"roadmap_create",description:"Создать реальный проект или веху Roadmap WesiOS.",parameters:{type:"object",required:["entityType","title","startDate","endDate"],properties:{entityType:{type:"string",enum:["project","item"]},projectId:{type:"string"},title:{type:"string"},description:{type:"string"},owner:{type:"string"},tags:{type:"array",items:{type:"string"}},kind:{type:"string",enum:["phase","milestone"]},status:{type:"string",enum:["planned","inProgress","blocked","done"]},assignee:{type:"string"},startDate:{type:"string"},endDate:{type:"string"},progress:{type:"integer",minimum:0,maximum:100},order:{type:"integer"},dependencyIds:{type:"array",items:{type:"string"}},linkedTaskIds:{type:"array",items:{type:"string"}}}}},
  {name:"roadmap_update",description:"Изменить реальный проект или веху Roadmap WesiOS. Меняй только явно указанные поля.",parameters:{type:"object",required:["entityType","id"],properties:{entityType:{type:"string",enum:["project","item"]},id:{type:"string"},projectId:{type:"string"},title:{type:"string"},description:{type:"string"},owner:{type:"string"},tags:{type:"array",items:{type:"string"}},kind:{type:"string",enum:["phase","milestone"]},status:{type:"string",enum:["planned","inProgress","blocked","done"]},assignee:{type:"string"},startDate:{type:"string"},endDate:{type:"string"},progress:{type:"integer",minimum:0,maximum:100},order:{type:"integer"},dependencyIds:{type:"array",items:{type:"string"}},linkedTaskIds:{type:"array",items:{type:"string"}}}}},
  {name:"roadmap_archive",description:"Архивировать проект или удалить веху Roadmap. DESTRUCTIVE: требуется отдельное подтверждение.",parameters:{type:"object",required:["entityType","id"],properties:{entityType:{type:"string",enum:["project","item"]},id:{type:"string"}}}},
 ];},
 context:function(){return{};},
 execute:function(e,ctx,name,args){if(!ctx.isOwner&&ctx.modules.indexOf("roadmap")<0)return{ok:false,code:"FORBIDDEN",message:"Нет доступа к Roadmap"};const input=args&&typeof args==="object"&&!Array.isArray(args)?args:{};const now=new Date().toISOString();
  if(name==="roadmap_list"){const projectId=String(input.projectId||"").trim(),includeArchived=input.includeArchived===true,limit=Math.max(1,Math.min(200,Math.trunc(Number(input.limit||100))));let projects=rows(e,ctx,"roadmap_projects").map(payload).filter((p)=>includeArchived||p.archived!==true);let items=rows(e,ctx,"roadmap_items").map(payload);if(projectId){projects=projects.filter((p)=>String(p.id||"")===projectId);items=items.filter((p)=>String(p.projectId||"")===projectId);}projects.sort((a,b)=>String(a.startDate||"").localeCompare(String(b.startDate||"")));items.sort((a,b)=>Number(a.order||0)-Number(b.order||0));return{ok:true,result:{projects:projects.slice(0,limit).map(safeProject),items:items.slice(0,limit).map(safeItem)}};}
  const entity=String(input.entityType||"");if(!["project","item"].includes(entity))return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный тип Roadmap-сущности"};const coll=entity==="project"?"roadmap_projects":"roadmap_items";
  if(name==="roadmap_create"){
   const title=String(input.title||"").trim();if(!title||title.length>500)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректное название"};const start=parseDate(input.startDate),end=parseDate(input.endDate);if(!start||!end||Date.parse(end)<Date.parse(start))return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный диапазон Roadmap"};const id="wai_roadmap_"+entity+"_"+Date.now()+"_"+$security.randomString(8);
   if(entity==="project"){const value={id,title,description:String(input.description||"").slice(0,20000),owner:String(input.owner||"").slice(0,500),tags:listStrings(input.tags,30),colorValue:0xFFF97316,startDate:start,endDate:end,createdAt:now,updatedAt:now,archived:false};saveNew(e,ctx,coll,id,value);return{ok:true,result:{roadmap:safeProject(value)}};}
   const projectId=String(input.projectId||"").trim();if(!projectId||!projectExists(e,ctx,projectId))return{ok:false,code:"NOT_FOUND",message:"Roadmap-проект не найден"};const kind=String(input.kind||"phase"),status=String(input.status||"planned");if(!["phase","milestone"].includes(kind)||!["planned","inProgress","blocked","done"].includes(status))return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный kind/status"};let progress=Math.max(0,Math.min(100,Math.trunc(Number(input.progress||0))));let normalizedStatus=status;if(progress>=100)normalizedStatus="done";if(normalizedStatus==="done"&&progress<100)progress=100;const deps=listStrings(input.dependencyIds).filter((x)=>x!==id);const value={id,projectId,title,description:String(input.description||"").slice(0,20000),kind,status:normalizedStatus,assignee:String(input.assignee||"").slice(0,180),startDate:start,endDate:end,progress,order:Math.trunc(Number(input.order||0)),dependencyIds:deps,linkedTaskIds:listStrings(input.linkedTaskIds),createdAt:now,updatedAt:now};saveNew(e,ctx,coll,id,value);return{ok:true,result:{roadmap:safeItem(value)}};
  }
  const id=String(input.id||"").trim();if(!id||id.length>180)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный id"};const record=recordById(e,ctx,coll,id);if(!record)return{ok:false,code:"NOT_FOUND",message:"Roadmap-запись не найдена"};const before=payload(record);
  if(name==="roadmap_archive"){if(entity==="project"){const next=Object.assign({},before,{archived:true,updatedAt:now});record.set("payload",next);record.set("stamp",now);record.set("deleted",false);e.app.save(record);return{ok:true,result:{roadmap:{id,archived:true}}};}record.set("deleted",true);record.set("stamp",now);e.app.save(record);return{ok:true,result:{roadmap:{id,deleted:true}}};}
  if(name!=="roadmap_update")return{ok:false,code:"UNKNOWN_TOOL",message:"Неизвестный Roadmap-инструмент"};const next=Object.assign({},before);next.id=String(before.id||id);
  if(Object.prototype.hasOwnProperty.call(input,"title")){const v=String(input.title||"").trim();if(!v||v.length>500)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректное название"};next.title=v;}if(Object.prototype.hasOwnProperty.call(input,"description"))next.description=String(input.description||"").slice(0,20000);if(Object.prototype.hasOwnProperty.call(input,"startDate")){const v=parseDate(input.startDate);if(!v)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректная дата начала"};next.startDate=v;}if(Object.prototype.hasOwnProperty.call(input,"endDate")){const v=parseDate(input.endDate);if(!v)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректная дата окончания"};next.endDate=v;}if(Date.parse(String(next.endDate||""))<Date.parse(String(next.startDate||"")))return{ok:false,code:"VALIDATION_ERROR",message:"Дата окончания раньше начала"};
  if(entity==="project"){if(Object.prototype.hasOwnProperty.call(input,"owner"))next.owner=String(input.owner||"").slice(0,500);if(Object.prototype.hasOwnProperty.call(input,"tags"))next.tags=listStrings(input.tags,30);}else{if(Object.prototype.hasOwnProperty.call(input,"projectId")){const p=String(input.projectId||"").trim();if(!p||!projectExists(e,ctx,p))return{ok:false,code:"NOT_FOUND",message:"Roadmap-проект не найден"};next.projectId=p;}if(Object.prototype.hasOwnProperty.call(input,"kind")){const v=String(input.kind||"");if(!["phase","milestone"].includes(v))return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный kind"};next.kind=v;}if(Object.prototype.hasOwnProperty.call(input,"status")){const v=String(input.status||"");if(!["planned","inProgress","blocked","done"].includes(v))return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный status"};next.status=v;}if(Object.prototype.hasOwnProperty.call(input,"progress")){const v=Number(input.progress);if(!Number.isFinite(v)||v<0||v>100)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный progress"};next.progress=Math.trunc(v);}if(next.progress>=100)next.status="done";if(next.status==="done"&&next.progress<100)next.progress=100;if(Object.prototype.hasOwnProperty.call(input,"assignee"))next.assignee=String(input.assignee||"").slice(0,180);if(Object.prototype.hasOwnProperty.call(input,"order"))next.order=Math.trunc(Number(input.order||0));if(Object.prototype.hasOwnProperty.call(input,"dependencyIds"))next.dependencyIds=listStrings(input.dependencyIds).filter((x)=>x!==id);if(Object.prototype.hasOwnProperty.call(input,"linkedTaskIds"))next.linkedTaskIds=listStrings(input.linkedTaskIds);}
  next.updatedAt=now;record.set("payload",next);record.set("stamp",now);record.set("deleted",false);e.app.save(record);return{ok:true,result:{roadmap:entity==="project"?safeProject(next):safeItem(next)}};
 }
};
