const ROOT_ORG = "org_wesi_inc";

function policy() { return require((typeof __hooks !== "undefined" ? __hooks + "/" : "./") + "wesi_ai_finance_policy.js"); }
function payload(record) { return policy().payload(record); }
function rows(e, ctx, coll) { try { return e.app.findRecordsByFilter("wesios_records", "owner={:owner} && coll={:coll} && deleted=false", "id", 0, 0, {owner:ctx.ownerId,coll}); } catch (_) { return []; } }
function recordById(e,ctx,id){try{return e.app.findFirstRecordByFilter("wesios_records","owner={:owner} && coll='transactions' && rid={:rid} && deleted=false",{owner:ctx.ownerId,rid:id});}catch(_){return null;}}
function grants(e,ctx){if(ctx.isOwner)return[];return rows(e,ctx,"organization_grants").map(payload).filter((g)=>String(g.employeeId||"")===ctx.employeeId);}
function parents(e,ctx){const out={};for(const row of rows(e,ctx,"organizations")){const p=payload(row),id=String(p.id||row.getString("rid")||"");if(id)out[id]=p.parentId==null?null:String(p.parentId);}return out;}
function grantApplies(e,ctx,orgId,permission){if(ctx.isOwner)return true;const gs=grants(e,ctx),ps=parents(e,ctx);let cursor=orgId,first=true;while(cursor){for(const g of gs){if(String(g.organizationId||"")!==cursor)continue;if(!first&&g.includeSubtree!==true)continue;const perms=Array.isArray(g.permissions)?g.permissions.map(String):[];if(perms.indexOf(permission)>=0)return true;}first=false;cursor=ps[cursor];}return false;}
function orgInfo(e,ctx,id){for(const row of rows(e,ctx,"organizations")){const p=payload(row),rid=String(p.id||row.getString("rid")||"");if(rid===id&&String(p.status||"active")!=="archived")return{id:rid,baseCurrency:String(p.baseCurrency||"RUB").toUpperCase()};}return null;}
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null;}
function parseDate(v){const d=new Date(String(v||""));return Number.isFinite(d.getTime())?d.toISOString():null;}
function normalizeMoney(input,org,existing){
  const hasAmount=Object.prototype.hasOwnProperty.call(input,"amount");
  const hasCurrency=Object.prototype.hasOwnProperty.call(input,"currency");
  const originalAmount=hasAmount?finite(input.amount):(existing?finite(existing.originalAmount!=null?existing.originalAmount:existing.amount):null);
  if(originalAmount==null||originalAmount<0)return{ok:false,message:"Некорректная сумма операции"};
  const currency=String(hasCurrency?input.currency:(existing&&existing.originalCurrency)||org.baseCurrency||"RUB").trim().toUpperCase();
  if(!/^[A-Z]{3,8}$/.test(currency))return{ok:false,message:"Некорректная валюта"};
  let fx=currency==="RUB"?1:finite(input.fxRateToReporting);
  if(currency!=="RUB"&&fx==null&&existing&&String(existing.originalCurrency||"").toUpperCase()===currency&&!hasAmount&&!hasCurrency)fx=finite(existing.fxRateToReporting);
  if(fx==null||fx<=0)return{ok:false,code:"WAI_FX_REQUIRED",message:"Для операции не в RUB нужен явный проверенный курс к RUB"};
  const reporting=Math.round(originalAmount*fx*100)/100;
  let baseAmount;
  if(currency===org.baseCurrency)baseAmount=originalAmount;
  else if(org.baseCurrency==="RUB")baseAmount=reporting;
  else {
    baseAmount=finite(input.organizationBaseAmount);
    if(baseAmount==null&&existing&&!hasAmount&&!hasCurrency)baseAmount=finite(existing.organizationBaseAmount);
    if(baseAmount==null||baseAmount<0)return{ok:false,code:"WAI_FX_REQUIRED",message:"Нужна проверенная сумма в базовой валюте организации"};
  }
  return{ok:true,originalAmount,originalCurrency:currency,amount:reporting,organizationBaseAmount:Math.round(baseAmount*100)/100,organizationBaseCurrency:org.baseCurrency,fxRateToReporting:fx};
}
function recurrence(input,existing){const recurring=Object.prototype.hasOwnProperty.call(input,"isRecurring")?input.isRecurring===true:existing?existing.isRecurring===true:false;let period=Object.prototype.hasOwnProperty.call(input,"recurringPeriod")?(input.recurringPeriod==null?null:String(input.recurringPeriod)):existing?existing.recurringPeriod:null;if(recurring&&["daily","weekly","monthly","yearly"].indexOf(String(period||""))<0)return{ok:false,message:"Для регулярной операции нужен корректный период"};if(!recurring)period=null;return{ok:true,isRecurring:recurring,recurringPeriod:period};}

module.exports={
 definitions:function(e,ctx){if(!policy().hasModule(ctx))return[];return[
  {name:"finance_transaction_create",description:"Создать реальную финансовую операцию WesiOS в разрешённой организации. Для валюты не RUB нужен проверенный fxRateToReporting; для иной базовой валюты также organizationBaseAmount.",parameters:{type:"object",required:["title","amount","type"],properties:{title:{type:"string"},amount:{type:"number"},type:{type:"string",enum:["income","expense"]},date:{type:"string"},category:{type:["string","null"]},description:{type:["string","null"]},organizationId:{type:"string"},accountId:{type:["string","null"]},currency:{type:"string"},fxRateToReporting:{type:"number"},organizationBaseAmount:{type:"number"},isRecurring:{type:"boolean"},recurringPeriod:{type:["string","null"],enum:["daily","weekly","monthly","yearly",null]}}}},
  {name:"finance_transaction_update",description:"Изменить разрешённую финансовую операцию WesiOS. Меняй только явно указанные поля.",parameters:{type:"object",required:["transactionId"],properties:{transactionId:{type:"string"},title:{type:"string"},amount:{type:"number"},type:{type:"string",enum:["income","expense"]},date:{type:"string"},category:{type:["string","null"]},description:{type:["string","null"]},accountId:{type:["string","null"]},currency:{type:"string"},fxRateToReporting:{type:"number"},organizationBaseAmount:{type:"number"},isRecurring:{type:"boolean"},recurringPeriod:{type:["string","null"],enum:["daily","weekly","monthly","yearly",null]}}}},
  {name:"finance_transaction_delete",description:"Удалить финансовую операцию WesiOS. DESTRUCTIVE: требуется отдельное подтверждение пользователя.",parameters:{type:"object",required:["transactionId"],properties:{transactionId:{type:"string"}}}},
 ];},context:function(){return{};},
 execute:function(e,ctx,name,args,activeOrganizationId){if(!policy().hasModule(ctx))return{ok:false,code:"FORBIDDEN",message:"Нет доступа к финансовому разделу"};const input=args&&typeof args==="object"&&!Array.isArray(args)?args:{};const now=new Date().toISOString();
  if(name==="finance_transaction_create"){
   const state=policy().access(e,ctx),orgId=policy().select(state,input.organizationId||activeOrganizationId);if(!orgId||!grantApplies(e,ctx,orgId,"create_transactions"))return{ok:false,code:"FORBIDDEN",message:"Нет права создавать операции этой организации"};const org=orgInfo(e,ctx,orgId);if(!org)return{ok:false,code:"NOT_FOUND",message:"Организация не найдена"};const title=String(input.title||"").trim();if(!title||title.length>500)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректное название операции"};const type=String(input.type||"");if(!["income","expense"].includes(type))return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный тип операции"};const money=normalizeMoney(input,org,null);if(!money.ok)return{ok:false,code:money.code||"VALIDATION_ERROR",message:money.message};const recurring=recurrence(input,null);if(!recurring.ok)return{ok:false,code:"VALIDATION_ERROR",message:recurring.message};if(recurring.isRecurring&&!grantApplies(e,ctx,orgId,"manage_recurring"))return{ok:false,code:"FORBIDDEN",message:"Нет права создавать регулярные операции"};const date=input.date?parseDate(input.date):now;if(!date)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректная дата операции"};const id="wai_transaction_"+Date.now()+"_"+$security.randomString(8);const value={id,title,amount:money.amount,type,date,category:input.category==null?null:String(input.category).slice(0,240),description:input.description==null?null:String(input.description).slice(0,10000),isRecurring:recurring.isRecurring,recurringPeriod:recurring.recurringPeriod,isAnomaly:false,zScore:null,accountId:input.accountId==null?null:String(input.accountId).slice(0,180),recurringAnchor:recurring.isRecurring?date:null,organizationId:orgId,projectId:null,counterpartyId:null,source:"manual",createdBy:ctx.employeeId,updatedBy:ctx.employeeId,updatedAt:now,ownerEmployeeId:ctx.employeeId,interOrgTransferId:null,createdByEmployeeId:ctx.employeeId,originalAmount:money.originalAmount,originalCurrency:money.originalCurrency,organizationBaseAmount:money.organizationBaseAmount,organizationBaseCurrency:money.organizationBaseCurrency,fxRateToReporting:money.fxRateToReporting,fxRateAt:money.originalCurrency==="RUB"?null:now,fxSource:money.originalCurrency==="RUB"?"manual-rub":"wesi-ai-explicit"};const c=e.app.findCollectionByNameOrId("wesios_records"),r=new Record(c);r.set("owner",ctx.ownerId);r.set("org","wesi-inc");r.set("coll","transactions");r.set("rid",id);r.set("payload",value);r.set("stamp",now);r.set("deleted",false);e.app.save(r);return{ok:true,result:{transaction:{id,title,type,amount:money.amount,originalAmount:money.originalAmount,originalCurrency:money.originalCurrency,organizationId:orgId,date}}};
  }
  const id=String(input.transactionId||"").trim();if(!id||id.length>180)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный transactionId"};const r=recordById(e,ctx,id);if(!r)return{ok:false,code:"NOT_FOUND",message:"Операция не найдена"};const before=payload(r),orgId=String(before.organizationId||ROOT_ORG);if(!grantApplies(e,ctx,orgId,"edit_transactions"))return{ok:false,code:"FORBIDDEN",message:"Нет права изменять операции этой организации"};if((before.isRecurring===true||input.isRecurring===true)&&!grantApplies(e,ctx,orgId,"manage_recurring"))return{ok:false,code:"FORBIDDEN",message:"Нет права изменять регулярные операции"};
  if(name==="finance_transaction_delete"){r.set("deleted",true);r.set("stamp",now);e.app.save(r);return{ok:true,result:{transaction:{id,deleted:true,organizationId:orgId}}};}
  if(name!=="finance_transaction_update")return{ok:false,code:"UNKNOWN_TOOL",message:"Неизвестный Finance-инструмент"};const org=orgInfo(e,ctx,orgId);if(!org)return{ok:false,code:"NOT_FOUND",message:"Организация не найдена"};const next=Object.assign({},before);if(Object.prototype.hasOwnProperty.call(input,"title")){const v=String(input.title||"").trim();if(!v||v.length>500)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректное название"};next.title=v;}if(Object.prototype.hasOwnProperty.call(input,"type")){const v=String(input.type||"");if(!["income","expense"].includes(v))return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный тип"};next.type=v;}if(Object.prototype.hasOwnProperty.call(input,"date")){const v=parseDate(input.date);if(!v)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректная дата"};next.date=v;}if(Object.prototype.hasOwnProperty.call(input,"category"))next.category=input.category==null?null:String(input.category).slice(0,240);if(Object.prototype.hasOwnProperty.call(input,"description"))next.description=input.description==null?null:String(input.description).slice(0,10000);if(Object.prototype.hasOwnProperty.call(input,"accountId"))next.accountId=input.accountId==null?null:String(input.accountId).slice(0,180);if(Object.prototype.hasOwnProperty.call(input,"amount")||Object.prototype.hasOwnProperty.call(input,"currency")){const m=normalizeMoney(input,org,before);if(!m.ok)return{ok:false,code:m.code||"VALIDATION_ERROR",message:m.message};Object.assign(next,m);next.fxRateAt=m.originalCurrency==="RUB"?null:now;next.fxSource=m.originalCurrency==="RUB"?"manual-rub":"wesi-ai-explicit";}const recurring=recurrence(input,before);if(!recurring.ok)return{ok:false,code:"VALIDATION_ERROR",message:recurring.message};next.isRecurring=recurring.isRecurring;next.recurringPeriod=recurring.recurringPeriod;if(recurring.isRecurring&&!next.recurringAnchor)next.recurringAnchor=next.date;next.updatedBy=ctx.employeeId;next.updatedAt=now;r.set("payload",next);r.set("stamp",now);r.set("deleted",false);e.app.save(r);return{ok:true,result:{transaction:{id,title:String(next.title||""),type:String(next.type||"expense"),amount:Number(next.amount||0),originalAmount:Number(next.originalAmount!=null?next.originalAmount:next.amount||0),originalCurrency:String(next.originalCurrency||"RUB"),organizationId:orgId,date:String(next.date||"")}}};
 }
};
