function payload(record){if(!record)return{};try{const raw=record.get("payload");if(raw&&typeof raw==="object"&&!Array.isArray(raw))return raw;if(typeof raw==="string"&&raw.trim())return JSON.parse(raw);}catch(_){}return{};}
function rows(e,ctx){try{return e.app.findRecordsByFilter("wesios_records","owner={:owner} && coll='audio_beats' && deleted=false","-stamp",5000,0,{owner:ctx.ownerId});}catch(_){return[];}}
function recordById(e,ctx,id){try{return e.app.findFirstRecordByFilter("wesios_records","owner={:owner} && coll='audio_beats' && rid={:rid} && deleted=false",{owner:ctx.ownerId,rid:id});}catch(_){return null;}}
function safeBeat(p){const lease=p.lease&&typeof p.lease==="object"?{id:String(p.lease.id||""),artistName:String(p.lease.artistName||""),socialUrl:String(p.lease.socialUrl||""),startsAt:p.lease.startsAt||null,endsAt:p.lease.endsAt||null,amount:Number(p.lease.amount||0),currency:String(p.lease.currency||"RUB"),notes:String(p.lease.notes||"")}:null;return{id:String(p.id||""),title:String(p.title||""),authorEmployeeId:String(p.authorEmployeeId||""),bpm:Number(p.bpm||0),musicalKey:String(p.musicalKey||""),genre:String(p.genre||""),mood:String(p.mood||""),tags:Array.isArray(p.tags)?p.tags.map(String).slice(0,40):[],stage:String(p.stage||"idea"),notes:String(p.notes||""),favorite:p.favorite===true,hasMp3:!!p.mp3Path,hasWav:!!p.wavPath,hasTrackout:!!p.trackoutPath,hasCover:!!p.coverPath,attachmentCount:Array.isArray(p.attachments)?p.attachments.length:0,comments:Array.isArray(p.comments)?p.comments.slice(-20).map((c)=>({id:String(c&&c.id||""),text:String(c&&c.text||"").slice(0,2000),authorId:String(c&&c.authorId||""),createdAt:c&&c.createdAt||null})):[],lease,createdAt:p.createdAt||null,updatedAt:p.updatedAt||null};}
function strings(v,max){if(!Array.isArray(v))return[];const out=[];for(const x of v.slice(0,max)){const s=String(x||"").trim().slice(0,120);if(s&&out.indexOf(s)<0)out.push(s);}return out;}
module.exports={
 definitions:function(e,ctx){if(!ctx.isOwner&&ctx.modules.indexOf("audio")<0)return[];return[
  {name:"audio_vault_list",description:"Прочитать синхронизированные метаданные Audio Vault WesiOS. Локальные пути к файлам не раскрываются модели.",parameters:{type:"object",properties:{query:{type:"string"},stage:{type:"string"},limit:{type:"integer",minimum:1,maximum:200}}}},
  {name:"audio_vault_update",description:"Изменить безопасные синхронизируемые метаданные бита Audio Vault или добавить комментарий. Пути/файлы и условия аренды этим инструментом не меняются.",parameters:{type:"object",required:["beatId"],properties:{beatId:{type:"string"},title:{type:"string"},bpm:{type:"integer",minimum:0,maximum:400},musicalKey:{type:"string"},genre:{type:"string"},mood:{type:"string"},tags:{type:"array",items:{type:"string"}},stage:{type:"string",enum:["idea","draft","production","mixing","mastering","ready","negotiating","leased","sold","exclusive","archived"]},notes:{type:"string"},favorite:{type:"boolean"},commentText:{type:"string"}}}},
 ];},context:function(){return{};},
 execute:function(e,ctx,name,args){if(!ctx.isOwner&&ctx.modules.indexOf("audio")<0)return{ok:false,code:"FORBIDDEN",message:"Нет доступа к Audio Vault"};const input=args&&typeof args==="object"&&!Array.isArray(args)?args:{};
  if(name==="audio_vault_list"){const q=String(input.query||"").trim().toLowerCase(),stage=String(input.stage||"").trim(),limit=Math.max(1,Math.min(200,Math.trunc(Number(input.limit||100))));let list=rows(e,ctx).map(payload);if(stage)list=list.filter((p)=>String(p.stage||"")===stage);if(q)list=list.filter((p)=>[p.title,p.genre,p.mood,p.musicalKey,p.notes].some((v)=>String(v||"").toLowerCase().includes(q))||(Array.isArray(p.tags)&&p.tags.some((v)=>String(v).toLowerCase().includes(q))));return{ok:true,result:{beats:list.slice(0,limit).map(safeBeat)}};}
  if(name!=="audio_vault_update")return{ok:false,code:"UNKNOWN_TOOL",message:"Неизвестный Audio Vault-инструмент"};const id=String(input.beatId||"").trim();if(!id||id.length>180)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный beatId"};const r=recordById(e,ctx,id);if(!r)return{ok:false,code:"NOT_FOUND",message:"Бит не найден"};const before=payload(r),next=Object.assign({},before),now=new Date().toISOString();
  if(Object.prototype.hasOwnProperty.call(input,"title")){const v=String(input.title||"").trim();if(!v||v.length>500)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректное название"};next.title=v;}if(Object.prototype.hasOwnProperty.call(input,"bpm")){const v=Number(input.bpm);if(!Number.isFinite(v)||v<0||v>400)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный BPM"};next.bpm=Math.trunc(v);}for(const f of ["musicalKey","genre","mood"]){if(Object.prototype.hasOwnProperty.call(input,f))next[f]=String(input[f]||"").slice(0,240);}if(Object.prototype.hasOwnProperty.call(input,"tags"))next.tags=strings(input.tags,40);if(Object.prototype.hasOwnProperty.call(input,"stage")){const v=String(input.stage||"");if(!["idea","draft","production","mixing","mastering","ready","negotiating","leased","sold","exclusive","archived"].includes(v))return{ok:false,code:"VALIDATION_ERROR",message:"Некорректная стадия бита"};next.stage=v;}if(Object.prototype.hasOwnProperty.call(input,"notes"))next.notes=String(input.notes||"").slice(0,30000);if(Object.prototype.hasOwnProperty.call(input,"favorite"))next.favorite=input.favorite===true;
  if(Object.prototype.hasOwnProperty.call(input,"commentText")){const text=String(input.commentText||"").trim();if(!text||text.length>4000)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный комментарий"};const comments=Array.isArray(next.comments)?next.comments.slice(0,500):[];comments.push({id:"wai_comment_"+Date.now()+"_"+$security.randomString(6),text,authorId:ctx.employeeId,createdAt:now});next.comments=comments;}
  // Local file paths, attachments and lease lifecycle are deliberately left untouched.
  next.updatedAt=now;r.set("payload",next);r.set("stamp",now);r.set("deleted",false);e.app.save(r);return{ok:true,result:{audio:safeBeat(next)}};
 }
};
