const GITHUB_COLL = "ai_github_connector";
function text(v){return String(v==null?"":v).trim();}
function lib(){return require(`${__hooks}/wesi_ai_github_lib.js`);}
function encryptionKey(){const key=text($os.getenv("WESI_GITHUB_CONNECTOR_KEY"));if(key.length!==32)throw new Error("GITHUB_CONNECTOR_NOT_CONFIGURED");return key;}
function payload(record){if(!record)return{};try{const raw=record.get("payload");if(raw&&typeof raw==="object"&&!Array.isArray(raw))return raw;if(typeof raw==="string"&&raw.trim())return JSON.parse(raw);}catch(_){}return{};}
function credentialRecord(e,ctx){try{return e.app.findFirstRecordByFilter("wesios_records","owner={:owner} && coll={:coll} && rid='github:credential' && deleted=false",{owner:ctx.ownerId,coll:GITHUB_COLL});}catch(_){return null;}}
function credential(e,ctx){const record=credentialRecord(e,ctx);if(!record)return null;const p=payload(record);let token="";try{token=String($security.decrypt(String(p.tokenCiphertext||""),encryptionKey()));}catch(_){return null;}if(token.length<20||token.length>512)return null;return{token,login:text(p.login),scopes:lib().uniqueScopes(p.scopes)};}
function statusCode(r){return Number(r&&(r.statusCode!=null?r.statusCode:r.status))||0;}
function apiGet(path,query,token,accept){const h=lib().safeHeaders(token);if(accept)h.Accept=accept;const r=$http.send({url:lib().apiUrl(path,query),method:"GET",headers:h,timeout:20});const code=statusCode(r);if(code===401||code===403)return{ok:false,code:"GITHUB_FORBIDDEN",message:"GitHub credential не имеет доступа к ресурсу"};if(code===404)return{ok:false,code:"NOT_FOUND",message:"GitHub ресурс не найден"};if(code<200||code>=300)return{ok:false,code:"GITHUB_UPSTREAM_ERROR",message:"GitHub API временно недоступен"};return{ok:true,response:r};}
function json(r){return lib().boundedResult(lib().parseJsonResponse(r),512*1024);}
function repoPair(input){try{return lib().validateOwnerRepo(input.owner,input.repo);}catch(_){return null;}}
function limit(input,max){const n=Math.trunc(Number(input.limit||30));return Math.max(1,Math.min(Number.isFinite(n)?n:30,max||100));}
function safeRepo(x){return{id:Number(x.id||0),name:text(x.name),fullName:text(x.full_name),private:x.private===true,defaultBranch:text(x.default_branch),description:text(x.description).slice(0,4000),htmlUrl:text(x.html_url),permissions:x.permissions&&typeof x.permissions==="object"?{admin:x.permissions.admin===true,maintain:x.permissions.maintain===true,push:x.permissions.push===true,triage:x.permissions.triage===true,pull:x.permissions.pull===true}:null,updatedAt:text(x.updated_at)||null};}
function safeBranch(x){return{name:text(x.name),sha:text(x.commit&&x.commit.sha),protected:x.protected===true};}
function safeCommit(x){const c=x.commit||{};return{sha:text(x.sha),message:text(c.message).slice(0,8000),author:text(c.author&&c.author.name),date:text(c.author&&c.author.date)||null,htmlUrl:text(x.html_url)};}
function safePr(x){return{number:Number(x.number||0),title:text(x.title).slice(0,1000),state:text(x.state),draft:x.draft===true,author:text(x.user&&x.user.login),head:text(x.head&&x.head.ref),base:text(x.base&&x.base.ref),mergeableState:text(x.mergeable_state),htmlUrl:text(x.html_url),updatedAt:text(x.updated_at)||null};}
function safeIssue(x){return{number:Number(x.number||0),title:text(x.title).slice(0,1000),state:text(x.state),author:text(x.user&&x.user.login),labels:Array.isArray(x.labels)?x.labels.slice(0,30).map((v)=>typeof v==="string"?v:text(v&&v.name)):[],htmlUrl:text(x.html_url),updatedAt:text(x.updated_at)||null};}
function safeRun(x){return{id:Number(x.id||0),name:text(x.name),event:text(x.event),status:text(x.status),conclusion:text(x.conclusion),branch:text(x.head_branch),sha:text(x.head_sha),workflowId:Number(x.workflow_id||0),htmlUrl:text(x.html_url),createdAt:text(x.created_at)||null,updatedAt:text(x.updated_at)||null};}

module.exports={
 definitions:function(e,ctx){if(!credentialRecord(e,ctx))return[];return[
  {name:"github_repositories_list",description:"Прочитать репозитории подключённого GitHub-аккаунта.",parameters:{type:"object",properties:{limit:{type:"integer",minimum:1,maximum:100}}}},
  {name:"github_file_read",description:"Прочитать один файл из GitHub-репозитория. Только фиксированный api.github.com, без произвольных URL.",parameters:{type:"object",required:["owner","repo","path"],properties:{owner:{type:"string"},repo:{type:"string"},path:{type:"string"},ref:{type:"string"}}}},
  {name:"github_branches_list",description:"Прочитать ветки GitHub-репозитория.",parameters:{type:"object",required:["owner","repo"],properties:{owner:{type:"string"},repo:{type:"string"},limit:{type:"integer",minimum:1,maximum:100}}}},
  {name:"github_commits_list",description:"Прочитать последние коммиты GitHub-репозитория.",parameters:{type:"object",required:["owner","repo"],properties:{owner:{type:"string"},repo:{type:"string"},sha:{type:"string"},limit:{type:"integer",minimum:1,maximum:100}}}},
  {name:"github_pull_requests_list",description:"Прочитать pull requests GitHub-репозитория.",parameters:{type:"object",required:["owner","repo"],properties:{owner:{type:"string"},repo:{type:"string"},state:{type:"string",enum:["open","closed","all"]},limit:{type:"integer",minimum:1,maximum:100}}}},
  {name:"github_issues_list",description:"Прочитать issues GitHub-репозитория, без pull requests.",parameters:{type:"object",required:["owner","repo"],properties:{owner:{type:"string"},repo:{type:"string"},state:{type:"string",enum:["open","closed","all"]},limit:{type:"integer",minimum:1,maximum:100}}}},
  {name:"github_actions_list",description:"Прочитать последние GitHub Actions workflow runs репозитория.",parameters:{type:"object",required:["owner","repo"],properties:{owner:{type:"string"},repo:{type:"string"},branch:{type:"string"},limit:{type:"integer",minimum:1,maximum:100}}}},
 ];},
 context:function(e,ctx){const c=credential(e,ctx);return c?{githubConnector:{connected:true,login:c.login,scopes:c.scopes}}:{};},
 execute:function(e,ctx,name,args){const c=credential(e,ctx);if(!c)return{ok:false,code:"GITHUB_NOT_CONNECTED",message:"GitHub не подключён"};const input=args&&typeof args==="object"&&!Array.isArray(args)?args:{};
  if(name==="github_repositories_list"){const r=apiGet("/user/repos",{per_page:limit(input,100),sort:"updated",affiliation:"owner,collaborator,organization_member"},c.token);if(!r.ok)return r;const data=json(r.response);return{ok:true,result:{repositories:(Array.isArray(data)?data:[]).map(safeRepo)}};}
  const pair=repoPair(input);if(!pair)return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный GitHub owner/repo"};const base=lib().repoApiPath(pair.owner,pair.repo,"");
  if(name==="github_file_read"){let p,ref;try{p=lib().validateContentPath(input.path);ref=lib().validateRef(input.ref||"HEAD");}catch(_){return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный GitHub path/ref"};}const r=apiGet(base+"/contents/"+p,{ref},c.token,"application/vnd.github.raw+json");if(!r.ok)return r;const raw=String(r.response.raw==null?"":r.response.raw);if(raw.length>256*1024)return{ok:false,code:"GITHUB_FILE_TOO_LARGE",message:"Файл слишком большой для AI-контекста"};return{ok:true,result:{owner:pair.owner,repo:pair.repo,path:String(input.path),ref,content:raw}};}
  if(name==="github_branches_list"){const r=apiGet(base+"/branches",{per_page:limit(input,100)},c.token);if(!r.ok)return r;const d=json(r.response);return{ok:true,result:{branches:(Array.isArray(d)?d:[]).map(safeBranch)}};}
  if(name==="github_commits_list"){let sha="";try{sha=input.sha?lib().validateRef(input.sha):"";}catch(_){return{ok:false,code:"VALIDATION_ERROR",message:"Некорректный GitHub ref"};}const r=apiGet(base+"/commits",{per_page:limit(input,100),sha},c.token);if(!r.ok)return r;const d=json(r.response);return{ok:true,result:{commits:(Array.isArray(d)?d:[]).map(safeCommit)}};}
  if(name==="github_pull_requests_list"){const state=["open","closed","all"].includes(String(input.state||"open"))?String(input.state||"open"):"open";const r=apiGet(base+"/pulls",{state,per_page:limit(input,100),sort:"updated",direction:"desc"},c.token);if(!r.ok)return r;const d=json(r.response);return{ok:true,result:{pullRequests:(Array.isArray(d)?d:[]).map(safePr)}};}
  if(name==="github_issues_list"){const state=["open","closed","all"].includes(String(input.state||"open"))?String(input.state||"open"):"open";const r=apiGet(base+"/issues",{state,per_page:limit(input,100),sort:"updated",direction:"desc"},c.token);if(!r.ok)return r;const d=json(r.response);return{ok:true,result:{issues:(Array.isArray(d)?d:[]).filter((x)=>!x.pull_request).map(safeIssue)}};}
  if(name==="github_actions_list"){let branch="";try{branch=input.branch?lib().validateRef(input.branch):"";}catch(_){return{ok:false,code:"VALIDATION_ERROR",message:"Некорректная GitHub branch"};}const r=apiGet(base+"/actions/runs",{per_page:limit(input,100),branch},c.token);if(!r.ok)return r;const d=json(r.response);return{ok:true,result:{workflowRuns:(Array.isArray(d.workflow_runs)?d.workflow_runs:[]).map(safeRun)}};}
  return{ok:false,code:"UNKNOWN_TOOL",message:"Неизвестный GitHub read-tool"};
 }
};