function payload(record){if(!record)return{};try{const raw=record.get("payload");if(raw&&typeof raw==="object"&&!Array.isArray(raw))return raw;if(typeof raw==="string"&&raw.trim())return JSON.parse(raw);}catch(_){}return{};}
function ownPermissions(e,ctx){if(ctx.isOwner)return{canManageTeam:true,canSeeOthersStats:true,modules:["contacts"]};let record=null;try{record=e.app.findFirstRecordByFilter("wesios_records","owner={:owner} && coll='employees' && rid={:rid} && deleted=false",{owner:ctx.ownerId,rid:ctx.employeeId});}catch(_){}const p=payload(record),perms=p.permissions&&typeof p.permissions==="object"?p.permissions:{};return{canManageTeam:perms.canManageTeam===true,canSeeOthersStats:perms.canSeeOthersStats===true,modules:Array.isArray(perms.modules)?perms.modules.map(String):[]};}
function rows(e,ctx){try{return e.app.findRecordsByFilter("wesios_records","owner={:owner} && coll='employees' && deleted=false","id",0,0,{owner:ctx.ownerId});}catch(_){return[];}}
function safe(p){return{id:String(p.id||""),login:String(p.login||""),fullName:String(p.fullName||""),nickname:String(p.nickname||""),position:String(p.position||""),phone:String(p.phone||""),email:String(p.email||""),socials:p.socials&&typeof p.socials==="object"&&!Array.isArray(p.socials)?p.socials:{},avatarIndex:Number(p.avatarIndex||0),createdAt:p.createdAt||null,skills:Array.isArray(p.skills)?p.skills.map(String).slice(0,80):[],weeklyCapacityPoints:Number(p.weeklyCapacityPoints==null?10:p.weeklyCapacityPoints),workloadMinRatio:Number(p.workloadMinRatio==null?.65:p.workloadMinRatio),workloadMaxRatio:Number(p.workloadMaxRatio==null?1.10:p.workloadMaxRatio),managerEmployeeId:p.managerEmployeeId==null?null:String(p.managerEmployeeId),workloadAlertTarget:String(p.workloadAlertTarget||"manager")};}
module.exports={
 definitions:function(e,ctx){const perms=ownPermissions(e,ctx);if(!ctx.isOwner&&!perms.canManageTeam&&!perms.canSeeOthersStats&&perms.modules.indexOf("contacts")<0)return[];return[{name:"team_list",description:"Прочитать безопасные публичные карточки сотрудников WesiOS. Пароли, соли, права, скрытые заметки, фото bytes и приватная статистика никогда не возвращаются.",parameters:{type:"object",properties:{query:{type:"string"},limit:{type:"integer",minimum:1,maximum:200}}}}];},
 context:function(){return{};},
 execute:function(e,ctx,name,args){if(name!=="team_list")return{ok:false,code:"UNKNOWN_TOOL",message:"Неизвестный Team-инструмент"};const perms=ownPermissions(e,ctx);if(!ctx.isOwner&&!perms.canManageTeam&&!perms.canSeeOthersStats&&perms.modules.indexOf("contacts")<0)return{ok:false,code:"FORBIDDEN",message:"Нет доступа к сотрудникам"};const input=args&&typeof args==="object"&&!Array.isArray(args)?args:{},q=String(input.query||"").trim().toLowerCase(),limit=Math.max(1,Math.min(200,Math.trunc(Number(input.limit||100))));let values=rows(e,ctx).map(payload).map(safe);if(q)values=values.filter((p)=>[p.id,p.login,p.fullName,p.nickname,p.position,p.email,p.phone].some((v)=>String(v||"").toLowerCase().includes(q))||p.skills.some((v)=>String(v).toLowerCase().includes(q)));values.sort((a,b)=>String(a.fullName||a.login).localeCompare(String(b.fullName||b.login),"ru"));return{ok:true,result:{employees:values.slice(0,limit)}};}
};
