from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if new in text:
        return text
    if old not in text:
        raise SystemExit(f'missing anchor: {label}')
    return text.replace(old, new, 1)


p = Path('lib/features/ai/backup/wesi_ai_backup_service.dart')
s = p.read_text(encoding='utf-8')

s = replace_once(
    s,
    '''    Archive archive;
    try {
      archive = ZipDecoder().decodeBytes(package, verify: true);
''',
    '''    _preflightZip(package);
    Archive archive;
    try {
      archive = ZipDecoder().decodeBytes(package, verify: true);
''',
    'zip preflight call',
)

anchor = '''  static Future<Map<String, String>> _restoreArtifacts(
'''
helpers = r'''  static void _preflightZip(Uint8List package) {
    const eocdSignature = 0x06054b50;
    const centralSignature = 0x02014b50;
    const maxCommentBytes = 65535;
    final data = ByteData.sublistView(package);
    final minEocd = 22;
    if (package.lengthInBytes < minEocd) {
      throw const FormatException('Повреждённый ZIP Wesi AI package');
    }

    int? eocdOffset;
    final searchStart = package.lengthInBytes - minEocd;
    final searchFloor = (package.lengthInBytes - minEocd - maxCommentBytes)
        .clamp(0, package.lengthInBytes);
    for (var offset = searchStart; offset >= searchFloor; offset--) {
      if (_u32(data, offset) == eocdSignature) {
        eocdOffset = offset;
        break;
      }
    }
    if (eocdOffset == null || eocdOffset + minEocd > package.lengthInBytes) {
      throw const FormatException('ZIP Wesi AI package не содержит EOCD');
    }

    final diskNumber = _u16(data, eocdOffset + 4);
    final centralDisk = _u16(data, eocdOffset + 6);
    final entriesOnDisk = _u16(data, eocdOffset + 8);
    final entriesTotal = _u16(data, eocdOffset + 10);
    final centralSize = _u32(data, eocdOffset + 12);
    final centralOffset = _u32(data, eocdOffset + 16);
    final commentLength = _u16(data, eocdOffset + 20);
    if (diskNumber != 0 ||
        centralDisk != 0 ||
        entriesOnDisk != entriesTotal ||
        entriesTotal <= 0 ||
        entriesTotal > maxArchiveEntries ||
        centralSize == 0xffffffff ||
        centralOffset == 0xffffffff ||
        eocdOffset + minEocd + commentLength != package.lengthInBytes ||
        centralOffset + centralSize > eocdOffset) {
      throw const FormatException('Неподдерживаемая структура ZIP Wesi AI package');
    }

    final names = <String>{};
    var offset = centralOffset;
    var declaredTotal = 0;
    for (var index = 0; index < entriesTotal; index++) {
      if (offset < 0 || offset + 46 > eocdOffset ||
          _u32(data, offset) != centralSignature) {
        throw const FormatException('Повреждён central directory Wesi AI package');
      }
      final flags = _u16(data, offset + 8);
      final compression = _u16(data, offset + 10);
      final compressedSize = _u32(data, offset + 20);
      final uncompressedSize = _u32(data, offset + 24);
      final nameLength = _u16(data, offset + 28);
      final extraLength = _u16(data, offset + 30);
      final fileCommentLength = _u16(data, offset + 32);
      final next = offset + 46 + nameLength + extraLength + fileCommentLength;
      if (next > eocdOffset ||
          nameLength <= 0 ||
          nameLength > 360 ||
          compressedSize == 0xffffffff ||
          uncompressedSize == 0xffffffff ||
          (flags & 0x1) != 0 ||
          (compression != 0 && compression != 8)) {
        throw const FormatException('Неподдерживаемая ZIP entry Wesi AI package');
      }
      String name;
      try {
        name = utf8
            .decode(Uint8List.sublistView(package, offset + 46, offset + 46 + nameLength))
            .replaceAll('\\', '/');
      } catch (_) {
        throw const FormatException('Некорректное имя ZIP entry Wesi AI package');
      }
      if (!_safeArchiveName(name) || !names.add(name)) {
        throw const FormatException('Дублированный или небезопасный ZIP path');
      }
      final perEntryLimit =
          name == 'manifest.json' ? 16 * 1024 * 1024 : maxArtifactBytes;
      if (uncompressedSize <= 0 || uncompressedSize > perEntryLimit) {
        throw const FormatException('ZIP entry превышает допустимый размер');
      }
      declaredTotal += uncompressedSize;
      if (declaredTotal > maxPackageBytes) {
        throw const FormatException('ZIP Wesi AI package превышает лимит распаковки');
      }
      // Reject pathological declared ratios before any decompression. The
      // canonical packages generated by WesiOS stay far below this boundary.
      if (compression == 8 &&
          compressedSize > 0 &&
          uncompressedSize > compressedSize * 1000) {
        throw const FormatException('Подозрительная степень сжатия ZIP entry');
      }
      offset = next;
    }
    if (offset != centralOffset + centralSize) {
      throw const FormatException('Некорректный размер central directory');
    }
    if (!names.contains('manifest.json')) {
      throw const FormatException('В Wesi AI package нет manifest.json');
    }
  }

  static int _u16(ByteData data, int offset) {
    if (offset < 0 || offset + 2 > data.lengthInBytes) {
      throw const FormatException('Повреждён ZIP Wesi AI package');
    }
    return data.getUint16(offset, Endian.little);
  }

  static int _u32(ByteData data, int offset) {
    if (offset < 0 || offset + 4 > data.lengthInBytes) {
      return -1;
    }
    return data.getUint32(offset, Endian.little);
  }

'''
s = replace_once(s, anchor, helpers + anchor, 'zip preflight helpers')
p.write_text(s, encoding='utf-8')

# Add regression cases without allocating a huge decompressed payload.
p = Path('test/wesi_ai_backup_d2d_test.dart')
s = p.read_text(encoding='utf-8')
idx = s.rfind('\n}')
if idx < 0:
    raise SystemExit('missing test main closing brace')
extra = r'''

  test('package decoder rejects duplicate archive names', () async {
    final manifest = utf8.encode(jsonEncode(<String, dynamic>{
      'format': 'wesi-ai-backup',
      'version': 1,
      'employeeId': 'employee_duplicate',
      'createdAt': DateTime(2026, 8, 15).toUtc().toIso8601String(),
      'projects': <dynamic>[],
      'conversations': <dynamic>[],
      'messages': <dynamic>[],
      'memoryEntries': <dynamic>[],
      'memorySettings': <String, dynamic>{},
      'conversationMemory': <dynamic>[],
      'artifacts': <dynamic>[],
    }));
    final archive = Archive()
      ..addFile(ArchiveFile('manifest.json', manifest.length, manifest))
      ..addFile(ArchiveFile('manifest.json', manifest.length, manifest));
    final encoded = ZipEncoder().encode(archive)!;
    expect(
      () => WesiAiBackupService.importPackage(
        package: Uint8List.fromList(encoded),
        current: WesiAiLocalState.empty('employee_duplicate'),
      ),
      throwsA(isA<FormatException>()),
    );
  });

  test('ZIP preflight rejects forged oversized declared entry before decode', () async {
    final source = await WesiAiBackupService.buildImportantPackage(
      _state('employee_declared_size'),
    );
    final bytes = Uint8List.fromList(source.packageBytes);
    const centralSignature = <int>[0x50, 0x4b, 0x01, 0x02];
    var central = -1;
    for (var i = 0; i <= bytes.length - centralSignature.length; i++) {
      var matches = true;
      for (var j = 0; j < centralSignature.length; j++) {
        if (bytes[i + j] != centralSignature[j]) {
          matches = false;
          break;
        }
      }
      if (matches) {
        central = i;
        break;
      }
    }
    expect(central, greaterThanOrEqualTo(0));
    final data = ByteData.sublistView(bytes);
    data.setUint32(
      central + 24,
      WesiAiBackupService.maxArtifactBytes + 1,
      Endian.little,
    );
    expect(
      () => WesiAiBackupService.importPackage(
        package: bytes,
        current: WesiAiLocalState.empty('employee_declared_size'),
      ),
      throwsA(isA<FormatException>()),
    );
  });
'''
s = s[:idx] + extra + s[idx:]
p.write_text(s, encoding='utf-8')
