name: Export Flutter Windows runner template

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  export:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: stable
      - name: Generate template
        run: flutter create --platforms=windows --project-name wesios /tmp/wesios_template
      - uses: actions/upload-artifact@v4
        with:
          name: flutter-3.24-windows-runner
          path: /tmp/wesios_template/windows/runner
          retention-days: 1
